### ISSUE TITLE
x-nullable value from $ref schema reference is not propageted

### ISSUE THREAD

**Issue by pakrym** [Azure/perks#109]
``` json
 "/array/complex/itemnull": {
      "get": {
        "operationId": "array_getComplexItemNull",
        "description": "Get array of complex type with null item [{'integer': 1 'string': '2'}, null, {'integer': 5, 'string': '6'}]",
        "tags": [
          "Array Operations"
        ],
        "responses": {
          "200": {
            "description": "Array of complex type with null item [{'integer': 1 'string': '2'}, null, {'integer': 5, 'string': '6'}]",
            "schema": {
              "description": "Array of complex type with null item [{'integer': 1 'string': '2'}, null, {'integer': 5, 'string': '6'}]",
              "type": "array",
              "items":
                {
                  "$ref": "#/definitions/Product",
                  "x-nullable": true
                }
            }
          },
          "default": {
            "description": "Unexpected error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
```

``` yml
    - !<!ArraySchema> &ref_109
      type: array
      apiVersions:
        - !<!ApiVersion> 
          version: 1.0.0
      elementType: *ref_24
      language: !<!Languages> 
        default:
          name: ArrayOfProduct
          description: 'Array of complex type with null item [{''integer'': 1 ''string'': ''2''}, null, {''integer'': 5, ''string'': ''6''}]'
```

**Comment by daviwil** [comment]
@pakrym as of the following two PRs I believe this issue is fixed:

- https://github.com/Azure/perks/pull/115
- https://github.com/Azure/autorest.modelerfour/pull/312

Could you try the test build here and let me know if the remaining `x-nullable` issues are resolved for you?

https://github.com/Azure/autorest.modelerfour/pull/312#issuecomment-654510326

**Comment by pakrym** [comment]
I think it didn't work with array items:

```
   "/array/complex/itemnull": {
      "get": {
        "operationId": "array_getComplexItemNull",
        "description": "Get array of complex type with null item [{'integer': 1 'string': '2'}, null, {'integer': 5, 'string': '6'}]",
        "tags": [
          "Array Operations"
        ],
        "responses": {
          "200": {
            "description": "Array of complex type with null item [{'integer': 1 'string': '2'}, null, {'integer': 5, 'string': '6'}]",
            "schema": {
              "description": "Array of complex type with null item [{'integer': 1 'string': '2'}, null, {'integer': 5, 'string': '6'}]",
              "type": "array",
              "items":
                {
                  "$ref": "#/definitions/Product",
                  "x-nullable": true
                }
            }
          },
          "default": {
            "description": "Unexpected error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
```


```
 - !<!ArraySchema> &ref_109
      type: array
      apiVersions:
        - !<!ApiVersion> 
          version: 1.0.0
      elementType: *ref_24
      language: !<!Languages> 
        default:
          name: ArrayOfProduct
          description: 'Array of complex type with null item [{''integer'': 1 ''string'': ''2''}, null, {''integer'': 5, ''string'': ''6''}]'
      protocol: !<!Protocols> {}
```

Or dictionaries:

```
    "/dictionary/complex/itemnull": {
      "get": {
        "operationId": "dictionary_getComplexItemNull",
        "description": "Get dictionary of complex type with null item {\"0\": {\"integer\": 1, \"string\": \"2\"}, \"1\": null, \"2\": {\"integer\": 5, \"string\": \"6\"}}",
        "tags": [
          "Dictionary Operations"
        ],
        "responses": {
          "200": {
            "description": "Dictionary of complex type with null item {\"0\": {\"integer\": 1, \"string\": \"2\"}, \"1\": null, \"2\": {\"integer\": 5, \"string\": \"6\"}}",
            "schema": {
              "description": "Dictionary of complex type with null item [{'integer': 1 'string': '2'}, null, {'integer': 5, 'string': '6'}]",
              "type": "object",
              "additionalProperties": {
                "$ref": "#/definitions/Widget",
                "x-nullable": true
              }
            }
          },
          "default": {
            "description": "Unexpected error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
```

```
 - !<!DictionarySchema> &ref_92
      type: dictionary
      elementType: *ref_13
      language: !<!Languages> 
        default:
          name: DictionaryOfWidget
          description: 'Dictionary of complex type with null item [{''integer'': 1 ''string'': ''2''}, null, {''integer'': 5, ''string'': ''6''}]'
      protocol: !<!Protocols> {}
```
