### ISSUE TITLE
HttpResponse mediaTypes and knownMediaType listed as required but are optional

### ISSUE THREAD

**Issue by tjprescott** [Azure/perks#123]
https://github.com/Azure/perks/blob/793ed8666e47821715eb2d45718fc9320419f0c4/codemodel/.resources/all-in-one/json/code-model.json#L2999

I'm running into this generated snippet from the v4 code model:

```yaml
            protocol: !<!Protocols> 
              http: !<!HttpResponse> 
                statusCodes:
                  - '200'
```

This is tagged as `HttpResponse`, and the definition of this schema in the code model says that both `mediaTypes` and `knownMediaTypes` are required. My understanding is that these properties should not be required in this scenario, and thus the code model is in error.

cc @sacheu @lmazuel
